---
galaxy_info:
  author: Jan "Khardix" StanÄ›k
  description: Common base for SSL/TLS server services
  issue_tracker_url: https://gitlab.com/khardix/server-setup/issues
  license: AGPLv3+
  min_ansible_version: 2.5
  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
